// Mocks generated by Mockito 5.4.6 from annotations
// in expense_tracker/test/notifiers/expense_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:expense_tracker/l10n/app_localizations.dart' as _i8;
import 'package:expense_tracker/models/expense_category.dart' as _i13;
import 'package:expense_tracker/models/expense_currency.dart' as _i12;
import 'package:expense_tracker/models/expense_model.dart' as _i4;
import 'package:expense_tracker/notifiers/notification_notifier.dart' as _i2;
import 'package:expense_tracker/services/expense_service.dart' as _i3;
import 'package:firebase_auth/firebase_auth.dart' as _i11;
import 'package:flutter/material.dart' as _i9;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:state_notifier/state_notifier.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNotificationState_0 extends _i1.SmartFake
    implements _i2.NotificationState {
  _FakeNotificationState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreateExpenseResult_1 extends _i1.SmartFake
    implements _i3.CreateExpenseResult {
  _FakeCreateExpenseResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEditExpenseResult_2 extends _i1.SmartFake
    implements _i3.EditExpenseResult {
  _FakeEditExpenseResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExpenseModel_3 extends _i1.SmartFake implements _i4.ExpenseModel {
  _FakeExpenseModel_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExpenseTotals_4 extends _i1.SmartFake implements _i3.ExpenseTotals {
  _FakeExpenseTotals_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBudgetCheckResult_5 extends _i1.SmartFake
    implements _i3.BudgetCheckResult {
  _FakeBudgetCheckResult_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NotificationNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationNotifier extends _i1.Mock
    implements _i2.NotificationNotifier {
  MockNotificationNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Ref get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _i6.dummyValue<_i5.Ref>(this, Invocation.getter(#ref)),
          )
          as _i5.Ref);

  @override
  _i2.NotificationState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeNotificationState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.NotificationState);

  @override
  set state(_i2.NotificationState? newState) => super.noSuchMethod(
    Invocation.setter(#state, newState),
    returnValueForMissingStub: null,
  );

  @override
  _i2.NotificationState build() =>
      (super.noSuchMethod(
            Invocation.method(#build, []),
            returnValue: _FakeNotificationState_0(
              this,
              Invocation.method(#build, []),
            ),
          )
          as _i2.NotificationState);

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> rescheduleNotifications(_i8.AppLocalizations? l10n) =>
      (super.noSuchMethod(
            Invocation.method(#rescheduleNotifications, [l10n]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> toggleDailyReminder(
    bool? enabled,
    _i8.AppLocalizations? l10n,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleDailyReminder, [enabled, l10n]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setReminderTime(
    _i9.TimeOfDay? time,
    _i8.AppLocalizations? l10n,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setReminderTime, [time, l10n]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> toggleLimitAlert(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#toggleLimitAlert, [enabled]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setMonthlyLimit(double? limit) =>
      (super.noSuchMethod(
            Invocation.method(#setMonthlyLimit, [limit]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> checkBudgetLimit({
    required double? currentMonthlySpent,
    required _i8.AppLocalizations? l10n,
    required String? currencySymbol,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkBudgetLimit, [], {
              #currentMonthlySpent: currentMonthlySpent,
              #l10n: l10n,
              #currencySymbol: currencySymbol,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> resetSettings() =>
      (super.noSuchMethod(
            Invocation.method(#resetSettings, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void runBuild() => super.noSuchMethod(
    Invocation.method(#runBuild, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.RemoveListener listenSelf(
    void Function(_i2.NotificationState?, _i2.NotificationState)? listener, {
    void Function(Object, StackTrace)? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listenSelf, [listener], {#onError: onError}),
            returnValue: () {},
          )
          as _i10.RemoveListener);

  @override
  bool updateShouldNotify(
    _i2.NotificationState? previous,
    _i2.NotificationState? next,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [previous, next]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [ExpenseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseService extends _i1.Mock implements _i3.ExpenseService {
  MockExpenseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i4.ExpenseModel>> loadUserExpenses({
    required _i11.User? user,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadUserExpenses, [], {#user: user}),
            returnValue: _i7.Future<List<_i4.ExpenseModel>>.value(
              <_i4.ExpenseModel>[],
            ),
          )
          as _i7.Future<List<_i4.ExpenseModel>>);

  @override
  _i7.Future<_i3.CreateExpenseResult> createExpense({
    required double? value,
    required String? description,
    required DateTime? date,
    required _i12.ExpenseCurrency? currency,
    required _i13.ExpenseCategory? category,
    required _i11.User? user,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createExpense, [], {
              #value: value,
              #description: description,
              #date: date,
              #currency: currency,
              #category: category,
              #user: user,
            }),
            returnValue: _i7.Future<_i3.CreateExpenseResult>.value(
              _FakeCreateExpenseResult_1(
                this,
                Invocation.method(#createExpense, [], {
                  #value: value,
                  #description: description,
                  #date: date,
                  #currency: currency,
                  #category: category,
                  #user: user,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.CreateExpenseResult>);

  @override
  _i7.Future<_i3.EditExpenseResult> editExpense(
    _i4.ExpenseModel? expenseModel, {
    required double? value,
    required String? description,
    required DateTime? date,
    required _i12.ExpenseCurrency? currency,
    required _i13.ExpenseCategory? category,
    required _i11.User? user,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #editExpense,
              [expenseModel],
              {
                #value: value,
                #description: description,
                #date: date,
                #currency: currency,
                #category: category,
                #user: user,
              },
            ),
            returnValue: _i7.Future<_i3.EditExpenseResult>.value(
              _FakeEditExpenseResult_2(
                this,
                Invocation.method(
                  #editExpense,
                  [expenseModel],
                  {
                    #value: value,
                    #description: description,
                    #date: date,
                    #currency: currency,
                    #category: category,
                    #user: user,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i3.EditExpenseResult>);

  @override
  _i7.Future<_i4.ExpenseModel> restoreExpense(
    _i4.ExpenseModel? expenseModel, {
    required _i11.User? user,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#restoreExpense, [expenseModel], {#user: user}),
            returnValue: _i7.Future<_i4.ExpenseModel>.value(
              _FakeExpenseModel_3(
                this,
                Invocation.method(
                  #restoreExpense,
                  [expenseModel],
                  {#user: user},
                ),
              ),
            ),
          )
          as _i7.Future<_i4.ExpenseModel>);

  @override
  _i7.Future<void> deleteExpense(
    _i4.ExpenseModel? expenseModel, {
    required _i11.User? user,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExpense, [expenseModel], {#user: user}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i3.ExpenseTotals calculateTotals(
    List<_i4.ExpenseModel>? expenses,
    _i12.ExpenseCurrency? targetCurrency,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculateTotals, [expenses, targetCurrency]),
            returnValue: _FakeExpenseTotals_4(
              this,
              Invocation.method(#calculateTotals, [expenses, targetCurrency]),
            ),
          )
          as _i3.ExpenseTotals);

  @override
  _i3.BudgetCheckResult checkBudgetStatus({
    required List<_i4.ExpenseModel>? expenses,
    required DateTime? expenseDate,
    required _i12.ExpenseCurrency? targetCurrency,
    required double? budgetLimit,
    required bool? alertEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkBudgetStatus, [], {
              #expenses: expenses,
              #expenseDate: expenseDate,
              #targetCurrency: targetCurrency,
              #budgetLimit: budgetLimit,
              #alertEnabled: alertEnabled,
            }),
            returnValue: _FakeBudgetCheckResult_5(
              this,
              Invocation.method(#checkBudgetStatus, [], {
                #expenses: expenses,
                #expenseDate: expenseDate,
                #targetCurrency: targetCurrency,
                #budgetLimit: budgetLimit,
                #alertEnabled: alertEnabled,
              }),
            ),
          )
          as _i3.BudgetCheckResult);

  @override
  _i3.BudgetCheckResult checkBudgetStatusForList({
    required List<_i4.ExpenseModel>? allExpenses,
    required List<_i4.ExpenseModel>? newExpenses,
    required _i12.ExpenseCurrency? targetCurrency,
    required double? budgetLimit,
    required bool? alertEnabled,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkBudgetStatusForList, [], {
              #allExpenses: allExpenses,
              #newExpenses: newExpenses,
              #targetCurrency: targetCurrency,
              #budgetLimit: budgetLimit,
              #alertEnabled: alertEnabled,
            }),
            returnValue: _FakeBudgetCheckResult_5(
              this,
              Invocation.method(#checkBudgetStatusForList, [], {
                #allExpenses: allExpenses,
                #newExpenses: newExpenses,
                #targetCurrency: targetCurrency,
                #budgetLimit: budgetLimit,
                #alertEnabled: alertEnabled,
              }),
            ),
          )
          as _i3.BudgetCheckResult);

  @override
  List<_i4.ExpenseModel> sortExpenses(
    List<_i4.ExpenseModel>? expenses,
    String? criteria,
    _i12.ExpenseCurrency? targetCurrency,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sortExpenses, [
              expenses,
              criteria,
              targetCurrency,
            ]),
            returnValue: <_i4.ExpenseModel>[],
          )
          as List<_i4.ExpenseModel>);

  @override
  Map<String, double> getExpensesByMonth(
    List<_i4.ExpenseModel>? expenses,
    _i12.ExpenseCurrency? targetCurrency,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExpensesByMonth, [expenses, targetCurrency]),
            returnValue: <String, double>{},
          )
          as Map<String, double>);

  @override
  Map<String, double> getExpensesByDay(
    List<_i4.ExpenseModel>? expenses,
    int? year,
    int? month,
    _i12.ExpenseCurrency? targetCurrency,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExpensesByDay, [
              expenses,
              year,
              month,
              targetCurrency,
            ]),
            returnValue: <String, double>{},
          )
          as Map<String, double>);

  @override
  List<_i4.ExpenseModel> getExpensesOfDay(
    List<_i4.ExpenseModel>? expenses,
    int? year,
    int? month,
    int? day,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExpensesOfDay, [expenses, year, month, day]),
            returnValue: <_i4.ExpenseModel>[],
          )
          as List<_i4.ExpenseModel>);

  @override
  Map<_i13.ExpenseCategory, double> getExpensesByCategoryForYear(
    List<_i4.ExpenseModel>? expenses,
    String? year,
    _i12.ExpenseCurrency? targetCurrency,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExpensesByCategoryForYear, [
              expenses,
              year,
              targetCurrency,
            ]),
            returnValue: <_i13.ExpenseCategory, double>{},
          )
          as Map<_i13.ExpenseCategory, double>);
}

/// A class which mocks [AppLocalizations].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalizations extends _i1.Mock implements _i8.AppLocalizations {
  MockAppLocalizations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get localeName =>
      (super.noSuchMethod(
            Invocation.getter(#localeName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#localeName),
            ),
          )
          as String);

  @override
  String get settingsTitle =>
      (super.noSuchMethod(
            Invocation.getter(#settingsTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#settingsTitle),
            ),
          )
          as String);

  @override
  String get appearance =>
      (super.noSuchMethod(
            Invocation.getter(#appearance),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#appearance),
            ),
          )
          as String);

  @override
  String get darkMode =>
      (super.noSuchMethod(
            Invocation.getter(#darkMode),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#darkMode),
            ),
          )
          as String);

  @override
  String get activated =>
      (super.noSuchMethod(
            Invocation.getter(#activated),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#activated),
            ),
          )
          as String);

  @override
  String get deactivated =>
      (super.noSuchMethod(
            Invocation.getter(#deactivated),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#deactivated),
            ),
          )
          as String);

  @override
  String get notifications =>
      (super.noSuchMethod(
            Invocation.getter(#notifications),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#notifications),
            ),
          )
          as String);

  @override
  String get dailyReminder =>
      (super.noSuchMethod(
            Invocation.getter(#dailyReminder),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#dailyReminder),
            ),
          )
          as String);

  @override
  String get reminderTime =>
      (super.noSuchMethod(
            Invocation.getter(#reminderTime),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#reminderTime),
            ),
          )
          as String);

  @override
  String get spendingLimitAlert =>
      (super.noSuchMethod(
            Invocation.getter(#spendingLimitAlert),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#spendingLimitAlert),
            ),
          )
          as String);

  @override
  String get monthlyLimit =>
      (super.noSuchMethod(
            Invocation.getter(#monthlyLimit),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#monthlyLimit),
            ),
          )
          as String);

  @override
  String get notificationsInfo =>
      (super.noSuchMethod(
            Invocation.getter(#notificationsInfo),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#notificationsInfo),
            ),
          )
          as String);

  @override
  String get currency =>
      (super.noSuchMethod(
            Invocation.getter(#currency),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#currency),
            ),
          )
          as String);

  @override
  String get defaultCurrency =>
      (super.noSuchMethod(
            Invocation.getter(#defaultCurrency),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#defaultCurrency),
            ),
          )
          as String);

  @override
  String get language =>
      (super.noSuchMethod(
            Invocation.getter(#language),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#language),
            ),
          )
          as String);

  @override
  String get defaultLanguage =>
      (super.noSuchMethod(
            Invocation.getter(#defaultLanguage),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#defaultLanguage),
            ),
          )
          as String);

  @override
  String get setMonthlyLimitTitle =>
      (super.noSuchMethod(
            Invocation.getter(#setMonthlyLimitTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#setMonthlyLimitTitle),
            ),
          )
          as String);

  @override
  String get insertAmountHint =>
      (super.noSuchMethod(
            Invocation.getter(#insertAmountHint),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#insertAmountHint),
            ),
          )
          as String);

  @override
  String get selectCurrencyTitle =>
      (super.noSuchMethod(
            Invocation.getter(#selectCurrencyTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#selectCurrencyTitle),
            ),
          )
          as String);

  @override
  String get selectLanguageTitle =>
      (super.noSuchMethod(
            Invocation.getter(#selectLanguageTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#selectLanguageTitle),
            ),
          )
          as String);

  @override
  String get languageNameIt =>
      (super.noSuchMethod(
            Invocation.getter(#languageNameIt),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#languageNameIt),
            ),
          )
          as String);

  @override
  String get languageNameEn =>
      (super.noSuchMethod(
            Invocation.getter(#languageNameEn),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#languageNameEn),
            ),
          )
          as String);

  @override
  String get languageNameFr =>
      (super.noSuchMethod(
            Invocation.getter(#languageNameFr),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#languageNameFr),
            ),
          )
          as String);

  @override
  String get languageNameEs =>
      (super.noSuchMethod(
            Invocation.getter(#languageNameEs),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#languageNameEs),
            ),
          )
          as String);

  @override
  String get languageNameDe =>
      (super.noSuchMethod(
            Invocation.getter(#languageNameDe),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#languageNameDe),
            ),
          )
          as String);

  @override
  String get languageNamePt =>
      (super.noSuchMethod(
            Invocation.getter(#languageNamePt),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#languageNamePt),
            ),
          )
          as String);

  @override
  String get newExpense =>
      (super.noSuchMethod(
            Invocation.getter(#newExpense),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#newExpense),
            ),
          )
          as String);

  @override
  String get ok =>
      (super.noSuchMethod(
            Invocation.getter(#ok),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#ok)),
          )
          as String);

  @override
  String get deleteDialogTitleSingle =>
      (super.noSuchMethod(
            Invocation.getter(#deleteDialogTitleSingle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#deleteDialogTitleSingle),
            ),
          )
          as String);

  @override
  String get deleteDialogTitleMultiple =>
      (super.noSuchMethod(
            Invocation.getter(#deleteDialogTitleMultiple),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#deleteDialogTitleMultiple),
            ),
          )
          as String);

  @override
  String get delete =>
      (super.noSuchMethod(
            Invocation.getter(#delete),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#delete),
            ),
          )
          as String);

  @override
  String get cancel =>
      (super.noSuchMethod(
            Invocation.getter(#cancel),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#cancel),
            ),
          )
          as String);

  @override
  String get undo =>
      (super.noSuchMethod(
            Invocation.getter(#undo),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#undo)),
          )
          as String);

  @override
  String get deletedTitleSingle =>
      (super.noSuchMethod(
            Invocation.getter(#deletedTitleSingle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#deletedTitleSingle),
            ),
          )
          as String);

  @override
  String get deletedTitleMultiple =>
      (super.noSuchMethod(
            Invocation.getter(#deletedTitleMultiple),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#deletedTitleMultiple),
            ),
          )
          as String);

  @override
  String get annualReport =>
      (super.noSuchMethod(
            Invocation.getter(#annualReport),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#annualReport),
            ),
          )
          as String);

  @override
  String get thisMonth =>
      (super.noSuchMethod(
            Invocation.getter(#thisMonth),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#thisMonth),
            ),
          )
          as String);

  @override
  String get today =>
      (super.noSuchMethod(
            Invocation.getter(#today),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#today),
            ),
          )
          as String);

  @override
  String get week =>
      (super.noSuchMethod(
            Invocation.getter(#week),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#week)),
          )
          as String);

  @override
  String get year =>
      (super.noSuchMethod(
            Invocation.getter(#year),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#year)),
          )
          as String);

  @override
  String get searchHint =>
      (super.noSuchMethod(
            Invocation.getter(#searchHint),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#searchHint),
            ),
          )
          as String);

  @override
  String get sortTitle =>
      (super.noSuchMethod(
            Invocation.getter(#sortTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#sortTitle),
            ),
          )
          as String);

  @override
  String get sortDateNewest =>
      (super.noSuchMethod(
            Invocation.getter(#sortDateNewest),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#sortDateNewest),
            ),
          )
          as String);

  @override
  String get sortDateOldest =>
      (super.noSuchMethod(
            Invocation.getter(#sortDateOldest),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#sortDateOldest),
            ),
          )
          as String);

  @override
  String get sortAmountHighest =>
      (super.noSuchMethod(
            Invocation.getter(#sortAmountHighest),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#sortAmountHighest),
            ),
          )
          as String);

  @override
  String get sortAmountLowest =>
      (super.noSuchMethod(
            Invocation.getter(#sortAmountLowest),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#sortAmountLowest),
            ),
          )
          as String);

  @override
  String get deleteConfirmMessageSwipe =>
      (super.noSuchMethod(
            Invocation.getter(#deleteConfirmMessageSwipe),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#deleteConfirmMessageSwipe),
            ),
          )
          as String);

  @override
  String get deleteSuccessMessageSwipe =>
      (super.noSuchMethod(
            Invocation.getter(#deleteSuccessMessageSwipe),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#deleteSuccessMessageSwipe),
            ),
          )
          as String);

  @override
  String get noDescription =>
      (super.noSuchMethod(
            Invocation.getter(#noDescription),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#noDescription),
            ),
          )
          as String);

  @override
  String get deselectAll =>
      (super.noSuchMethod(
            Invocation.getter(#deselectAll),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#deselectAll),
            ),
          )
          as String);

  @override
  String get selectAll =>
      (super.noSuchMethod(
            Invocation.getter(#selectAll),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#selectAll),
            ),
          )
          as String);

  @override
  String get deleteSelectedTooltip =>
      (super.noSuchMethod(
            Invocation.getter(#deleteSelectedTooltip),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#deleteSelectedTooltip),
            ),
          )
          as String);

  @override
  String get descriptionHint =>
      (super.noSuchMethod(
            Invocation.getter(#descriptionHint),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#descriptionHint),
            ),
          )
          as String);

  @override
  String get deleteConfirmTitle =>
      (super.noSuchMethod(
            Invocation.getter(#deleteConfirmTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#deleteConfirmTitle),
            ),
          )
          as String);

  @override
  String get errorTitle =>
      (super.noSuchMethod(
            Invocation.getter(#errorTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#errorTitle),
            ),
          )
          as String);

  @override
  String get zeroValueError =>
      (super.noSuchMethod(
            Invocation.getter(#zeroValueError),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#zeroValueError),
            ),
          )
          as String);

  @override
  String get createdTitle =>
      (super.noSuchMethod(
            Invocation.getter(#createdTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#createdTitle),
            ),
          )
          as String);

  @override
  String get editedTitle =>
      (super.noSuchMethod(
            Invocation.getter(#editedTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#editedTitle),
            ),
          )
          as String);

  @override
  String get expenseCreated =>
      (super.noSuchMethod(
            Invocation.getter(#expenseCreated),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#expenseCreated),
            ),
          )
          as String);

  @override
  String get expenseEdited =>
      (super.noSuchMethod(
            Invocation.getter(#expenseEdited),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#expenseEdited),
            ),
          )
          as String);

  @override
  String get expenseInstructionTitle =>
      (super.noSuchMethod(
            Invocation.getter(#expenseInstructionTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#expenseInstructionTitle),
            ),
          )
          as String);

  @override
  String get expenseInstructionMessage =>
      (super.noSuchMethod(
            Invocation.getter(#expenseInstructionMessage),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#expenseInstructionMessage),
            ),
          )
          as String);

  @override
  String get profileTitle =>
      (super.noSuchMethod(
            Invocation.getter(#profileTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#profileTitle),
            ),
          )
          as String);

  @override
  String get dataUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#dataUpdated),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#dataUpdated),
            ),
          )
          as String);

  @override
  String get profilePictureUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#profilePictureUpdated),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#profilePictureUpdated),
            ),
          )
          as String);

  @override
  String get removePictureTitle =>
      (super.noSuchMethod(
            Invocation.getter(#removePictureTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#removePictureTitle),
            ),
          )
          as String);

  @override
  String get removePictureMessage =>
      (super.noSuchMethod(
            Invocation.getter(#removePictureMessage),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#removePictureMessage),
            ),
          )
          as String);

  @override
  String get pictureRemoved =>
      (super.noSuchMethod(
            Invocation.getter(#pictureRemoved),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#pictureRemoved),
            ),
          )
          as String);

  @override
  String get nameLabel =>
      (super.noSuchMethod(
            Invocation.getter(#nameLabel),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#nameLabel),
            ),
          )
          as String);

  @override
  String get editNameTooltip =>
      (super.noSuchMethod(
            Invocation.getter(#editNameTooltip),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#editNameTooltip),
            ),
          )
          as String);

  @override
  String get emailLabel =>
      (super.noSuchMethod(
            Invocation.getter(#emailLabel),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#emailLabel),
            ),
          )
          as String);

  @override
  String get editEmailTooltip =>
      (super.noSuchMethod(
            Invocation.getter(#editEmailTooltip),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#editEmailTooltip),
            ),
          )
          as String);

  @override
  String get passwordLabel =>
      (super.noSuchMethod(
            Invocation.getter(#passwordLabel),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#passwordLabel),
            ),
          )
          as String);

  @override
  String get editPasswordTooltip =>
      (super.noSuchMethod(
            Invocation.getter(#editPasswordTooltip),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#editPasswordTooltip),
            ),
          )
          as String);

  @override
  String get userIdLabel =>
      (super.noSuchMethod(
            Invocation.getter(#userIdLabel),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#userIdLabel),
            ),
          )
          as String);

  @override
  String get copyIdTooltip =>
      (super.noSuchMethod(
            Invocation.getter(#copyIdTooltip),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#copyIdTooltip),
            ),
          )
          as String);

  @override
  String get idCopied =>
      (super.noSuchMethod(
            Invocation.getter(#idCopied),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#idCopied),
            ),
          )
          as String);

  @override
  String get deleteAccountButton =>
      (super.noSuchMethod(
            Invocation.getter(#deleteAccountButton),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#deleteAccountButton),
            ),
          )
          as String);

  @override
  String get deleteAccountTitle =>
      (super.noSuchMethod(
            Invocation.getter(#deleteAccountTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#deleteAccountTitle),
            ),
          )
          as String);

  @override
  String get deleteAccountMessage =>
      (super.noSuchMethod(
            Invocation.getter(#deleteAccountMessage),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#deleteAccountMessage),
            ),
          )
          as String);

  @override
  String get accountDeleted =>
      (super.noSuchMethod(
            Invocation.getter(#accountDeleted),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#accountDeleted),
            ),
          )
          as String);

  @override
  String get save =>
      (super.noSuchMethod(
            Invocation.getter(#save),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#save)),
          )
          as String);

  @override
  String get newNameHint =>
      (super.noSuchMethod(
            Invocation.getter(#newNameHint),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#newNameHint),
            ),
          )
          as String);

  @override
  String get nameUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#nameUpdated),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#nameUpdated),
            ),
          )
          as String);

  @override
  String get newEmailHint =>
      (super.noSuchMethod(
            Invocation.getter(#newEmailHint),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#newEmailHint),
            ),
          )
          as String);

  @override
  String get currentPasswordHint =>
      (super.noSuchMethod(
            Invocation.getter(#currentPasswordHint),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#currentPasswordHint),
            ),
          )
          as String);

  @override
  String get invalidData =>
      (super.noSuchMethod(
            Invocation.getter(#invalidData),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#invalidData),
            ),
          )
          as String);

  @override
  String get emailUpdateSent =>
      (super.noSuchMethod(
            Invocation.getter(#emailUpdateSent),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#emailUpdateSent),
            ),
          )
          as String);

  @override
  String get newPasswordHint =>
      (super.noSuchMethod(
            Invocation.getter(#newPasswordHint),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#newPasswordHint),
            ),
          )
          as String);

  @override
  String get confirmPasswordHint =>
      (super.noSuchMethod(
            Invocation.getter(#confirmPasswordHint),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#confirmPasswordHint),
            ),
          )
          as String);

  @override
  String get passwordsDoNotMatch =>
      (super.noSuchMethod(
            Invocation.getter(#passwordsDoNotMatch),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#passwordsDoNotMatch),
            ),
          )
          as String);

  @override
  String get passwordUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#passwordUpdated),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#passwordUpdated),
            ),
          )
          as String);

  @override
  String get notAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#notAvailable),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#notAvailable),
            ),
          )
          as String);

  @override
  String get yearsPageTitle =>
      (super.noSuchMethod(
            Invocation.getter(#yearsPageTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#yearsPageTitle),
            ),
          )
          as String);

  @override
  String get noExpensesTitle =>
      (super.noSuchMethod(
            Invocation.getter(#noExpensesTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#noExpensesTitle),
            ),
          )
          as String);

  @override
  String get noExpensesSubtitle =>
      (super.noSuchMethod(
            Invocation.getter(#noExpensesSubtitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#noExpensesSubtitle),
            ),
          )
          as String);

  @override
  String get monthlyDetail =>
      (super.noSuchMethod(
            Invocation.getter(#monthlyDetail),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#monthlyDetail),
            ),
          )
          as String);

  @override
  String get noExpensesMonthTitle =>
      (super.noSuchMethod(
            Invocation.getter(#noExpensesMonthTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#noExpensesMonthTitle),
            ),
          )
          as String);

  @override
  String get dailyExpenses =>
      (super.noSuchMethod(
            Invocation.getter(#dailyExpenses),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#dailyExpenses),
            ),
          )
          as String);

  @override
  String get noExpensesDayTitle =>
      (super.noSuchMethod(
            Invocation.getter(#noExpensesDayTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#noExpensesDayTitle),
            ),
          )
          as String);

  @override
  String get totalDayLabel =>
      (super.noSuchMethod(
            Invocation.getter(#totalDayLabel),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#totalDayLabel),
            ),
          )
          as String);

  @override
  String get allExpenses =>
      (super.noSuchMethod(
            Invocation.getter(#allExpenses),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#allExpenses),
            ),
          )
          as String);

  @override
  String get confirm =>
      (super.noSuchMethod(
            Invocation.getter(#confirm),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#confirm),
            ),
          )
          as String);

  @override
  String get dontShowAgain =>
      (super.noSuchMethod(
            Invocation.getter(#dontShowAgain),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#dontShowAgain),
            ),
          )
          as String);

  @override
  String get selectYear =>
      (super.noSuchMethod(
            Invocation.getter(#selectYear),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#selectYear),
            ),
          )
          as String);

  @override
  String get logout =>
      (super.noSuchMethod(
            Invocation.getter(#logout),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#logout),
            ),
          )
          as String);

  @override
  String get logoutConfirmTitle =>
      (super.noSuchMethod(
            Invocation.getter(#logoutConfirmTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#logoutConfirmTitle),
            ),
          )
          as String);

  @override
  String get logoutConfirmMessage =>
      (super.noSuchMethod(
            Invocation.getter(#logoutConfirmMessage),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#logoutConfirmMessage),
            ),
          )
          as String);

  @override
  String get close =>
      (super.noSuchMethod(
            Invocation.getter(#close),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#close),
            ),
          )
          as String);

  @override
  String get forgotPassword =>
      (super.noSuchMethod(
            Invocation.getter(#forgotPassword),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#forgotPassword),
            ),
          )
          as String);

  @override
  String get accountFallback =>
      (super.noSuchMethod(
            Invocation.getter(#accountFallback),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#accountFallback),
            ),
          )
          as String);

  @override
  String get appInitErrorTitle =>
      (super.noSuchMethod(
            Invocation.getter(#appInitErrorTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#appInitErrorTitle),
            ),
          )
          as String);

  @override
  String get appInitErrorMessage =>
      (super.noSuchMethod(
            Invocation.getter(#appInitErrorMessage),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#appInitErrorMessage),
            ),
          )
          as String);

  @override
  String get retry =>
      (super.noSuchMethod(
            Invocation.getter(#retry),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#retry),
            ),
          )
          as String);

  @override
  String get authAppTitle =>
      (super.noSuchMethod(
            Invocation.getter(#authAppTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#authAppTitle),
            ),
          )
          as String);

  @override
  String get authAppSubtitle =>
      (super.noSuchMethod(
            Invocation.getter(#authAppSubtitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#authAppSubtitle),
            ),
          )
          as String);

  @override
  String get loginTab =>
      (super.noSuchMethod(
            Invocation.getter(#loginTab),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#loginTab),
            ),
          )
          as String);

  @override
  String get registerTab =>
      (super.noSuchMethod(
            Invocation.getter(#registerTab),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#registerTab),
            ),
          )
          as String);

  @override
  String get welcomeBack =>
      (super.noSuchMethod(
            Invocation.getter(#welcomeBack),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#welcomeBack),
            ),
          )
          as String);

  @override
  String get signInToContinue =>
      (super.noSuchMethod(
            Invocation.getter(#signInToContinue),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#signInToContinue),
            ),
          )
          as String);

  @override
  String get emailHint =>
      (super.noSuchMethod(
            Invocation.getter(#emailHint),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#emailHint),
            ),
          )
          as String);

  @override
  String get emailRequired =>
      (super.noSuchMethod(
            Invocation.getter(#emailRequired),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#emailRequired),
            ),
          )
          as String);

  @override
  String get emailInvalid =>
      (super.noSuchMethod(
            Invocation.getter(#emailInvalid),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#emailInvalid),
            ),
          )
          as String);

  @override
  String get passwordHint =>
      (super.noSuchMethod(
            Invocation.getter(#passwordHint),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#passwordHint),
            ),
          )
          as String);

  @override
  String get passwordRequired =>
      (super.noSuchMethod(
            Invocation.getter(#passwordRequired),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#passwordRequired),
            ),
          )
          as String);

  @override
  String get loginButton =>
      (super.noSuchMethod(
            Invocation.getter(#loginButton),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#loginButton),
            ),
          )
          as String);

  @override
  String get emailNotVerifiedTitle =>
      (super.noSuchMethod(
            Invocation.getter(#emailNotVerifiedTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#emailNotVerifiedTitle),
            ),
          )
          as String);

  @override
  String get emailNotVerifiedMessage =>
      (super.noSuchMethod(
            Invocation.getter(#emailNotVerifiedMessage),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#emailNotVerifiedMessage),
            ),
          )
          as String);

  @override
  String get resendEmail =>
      (super.noSuchMethod(
            Invocation.getter(#resendEmail),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#resendEmail),
            ),
          )
          as String);

  @override
  String get verificationEmailSent =>
      (super.noSuchMethod(
            Invocation.getter(#verificationEmailSent),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#verificationEmailSent),
            ),
          )
          as String);

  @override
  String get insertEmailForRecovery =>
      (super.noSuchMethod(
            Invocation.getter(#insertEmailForRecovery),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#insertEmailForRecovery),
            ),
          )
          as String);

  @override
  String get createAccount =>
      (super.noSuchMethod(
            Invocation.getter(#createAccount),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#createAccount),
            ),
          )
          as String);

  @override
  String get registerToStart =>
      (super.noSuchMethod(
            Invocation.getter(#registerToStart),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#registerToStart),
            ),
          )
          as String);

  @override
  String get fullNameHint =>
      (super.noSuchMethod(
            Invocation.getter(#fullNameHint),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#fullNameHint),
            ),
          )
          as String);

  @override
  String get nameRequired =>
      (super.noSuchMethod(
            Invocation.getter(#nameRequired),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#nameRequired),
            ),
          )
          as String);

  @override
  String get passwordMinLength =>
      (super.noSuchMethod(
            Invocation.getter(#passwordMinLength),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#passwordMinLength),
            ),
          )
          as String);

  @override
  String get confirmPasswordRequired =>
      (super.noSuchMethod(
            Invocation.getter(#confirmPasswordRequired),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#confirmPasswordRequired),
            ),
          )
          as String);

  @override
  String get registerButton =>
      (super.noSuchMethod(
            Invocation.getter(#registerButton),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#registerButton),
            ),
          )
          as String);

  @override
  String get verifyEmailTitle =>
      (super.noSuchMethod(
            Invocation.getter(#verifyEmailTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#verifyEmailTitle),
            ),
          )
          as String);

  @override
  String get verifyEmailContent =>
      (super.noSuchMethod(
            Invocation.getter(#verifyEmailContent),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#verifyEmailContent),
            ),
          )
          as String);

  @override
  String get notificationDailyTitle =>
      (super.noSuchMethod(
            Invocation.getter(#notificationDailyTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#notificationDailyTitle),
            ),
          )
          as String);

  @override
  String get notificationDailyBody =>
      (super.noSuchMethod(
            Invocation.getter(#notificationDailyBody),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#notificationDailyBody),
            ),
          )
          as String);

  @override
  String get notificationBudgetTitle =>
      (super.noSuchMethod(
            Invocation.getter(#notificationBudgetTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#notificationBudgetTitle),
            ),
          )
          as String);

  @override
  String get editExpenseConvertedTitle =>
      (super.noSuchMethod(
            Invocation.getter(#editExpenseConvertedTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#editExpenseConvertedTitle),
            ),
          )
          as String);

  @override
  String get warningOfflineCurrencyCreate =>
      (super.noSuchMethod(
            Invocation.getter(#warningOfflineCurrencyCreate),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#warningOfflineCurrencyCreate),
            ),
          )
          as String);

  @override
  String get warningOfflineCurrencyEdit =>
      (super.noSuchMethod(
            Invocation.getter(#warningOfflineCurrencyEdit),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#warningOfflineCurrencyEdit),
            ),
          )
          as String);

  @override
  String get warningTitle =>
      (super.noSuchMethod(
            Invocation.getter(#warningTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#warningTitle),
            ),
          )
          as String);

  @override
  String get conversionUnavailable =>
      (super.noSuchMethod(
            Invocation.getter(#conversionUnavailable),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#conversionUnavailable),
            ),
          )
          as String);

  @override
  String get retryWhenOnline =>
      (super.noSuchMethod(
            Invocation.getter(#retryWhenOnline),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#retryWhenOnline),
            ),
          )
          as String);

  @override
  String get categoryFood =>
      (super.noSuchMethod(
            Invocation.getter(#categoryFood),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#categoryFood),
            ),
          )
          as String);

  @override
  String get categoryTransport =>
      (super.noSuchMethod(
            Invocation.getter(#categoryTransport),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#categoryTransport),
            ),
          )
          as String);

  @override
  String get categoryHome =>
      (super.noSuchMethod(
            Invocation.getter(#categoryHome),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#categoryHome),
            ),
          )
          as String);

  @override
  String get categoryHealth =>
      (super.noSuchMethod(
            Invocation.getter(#categoryHealth),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#categoryHealth),
            ),
          )
          as String);

  @override
  String get categoryEntertainment =>
      (super.noSuchMethod(
            Invocation.getter(#categoryEntertainment),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#categoryEntertainment),
            ),
          )
          as String);

  @override
  String get categoryShopping =>
      (super.noSuchMethod(
            Invocation.getter(#categoryShopping),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#categoryShopping),
            ),
          )
          as String);

  @override
  String get categoryEducation =>
      (super.noSuchMethod(
            Invocation.getter(#categoryEducation),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#categoryEducation),
            ),
          )
          as String);

  @override
  String get categoryTravel =>
      (super.noSuchMethod(
            Invocation.getter(#categoryTravel),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#categoryTravel),
            ),
          )
          as String);

  @override
  String get categoryOther =>
      (super.noSuchMethod(
            Invocation.getter(#categoryOther),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#categoryOther),
            ),
          )
          as String);

  @override
  String get deleteAccountMessageConfirm =>
      (super.noSuchMethod(
            Invocation.getter(#deleteAccountMessageConfirm),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#deleteAccountMessageConfirm),
            ),
          )
          as String);

  @override
  String get monthlyTrend =>
      (super.noSuchMethod(
            Invocation.getter(#monthlyTrend),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#monthlyTrend),
            ),
          )
          as String);

  @override
  String get categoryBreakdown =>
      (super.noSuchMethod(
            Invocation.getter(#categoryBreakdown),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#categoryBreakdown),
            ),
          )
          as String);

  @override
  String get emptyExpensesTitle =>
      (super.noSuchMethod(
            Invocation.getter(#emptyExpensesTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#emptyExpensesTitle),
            ),
          )
          as String);

  @override
  String get emptyExpensesSubtitle =>
      (super.noSuchMethod(
            Invocation.getter(#emptyExpensesSubtitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#emptyExpensesSubtitle),
            ),
          )
          as String);

  @override
  String get emptySearchTitle =>
      (super.noSuchMethod(
            Invocation.getter(#emptySearchTitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#emptySearchTitle),
            ),
          )
          as String);

  @override
  String get emptySearchSubtitle =>
      (super.noSuchMethod(
            Invocation.getter(#emptySearchSubtitle),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#emptySearchSubtitle),
            ),
          )
          as String);

  @override
  String activeAt(String? time) =>
      (super.noSuchMethod(
            Invocation.method(#activeAt, [time]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#activeAt, [time]),
            ),
          )
          as String);

  @override
  String activeMonthlyLimit(String? amount) =>
      (super.noSuchMethod(
            Invocation.method(#activeMonthlyLimit, [amount]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#activeMonthlyLimit, [amount]),
            ),
          )
          as String);

  @override
  String deleteConfirmMessage(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConfirmMessage, [count]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#deleteConfirmMessage, [count]),
            ),
          )
          as String);

  @override
  String deleteSuccessMessage(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSuccessMessage, [count]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#deleteSuccessMessage, [count]),
            ),
          )
          as String);

  @override
  String selectedCountLabel(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#selectedCountLabel, [count]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#selectedCountLabel, [count]),
            ),
          )
          as String);

  @override
  String refreshError(String? error) =>
      (super.noSuchMethod(
            Invocation.method(#refreshError, [error]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#refreshError, [error]),
            ),
          )
          as String);

  @override
  String recoveryEmailSent(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#recoveryEmailSent, [email]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#recoveryEmailSent, [email]),
            ),
          )
          as String);

  @override
  String totalYearLabel(String? year) =>
      (super.noSuchMethod(
            Invocation.method(#totalYearLabel, [year]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#totalYearLabel, [year]),
            ),
          )
          as String);

  @override
  String totalMonthLabel(String? month) =>
      (super.noSuchMethod(
            Invocation.method(#totalMonthLabel, [month]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#totalMonthLabel, [month]),
            ),
          )
          as String);

  @override
  String dayCountLabel(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#dayCountLabel, [count]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#dayCountLabel, [count]),
            ),
          )
          as String);

  @override
  String expenseCountLabel(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#expenseCountLabel, [count]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#expenseCountLabel, [count]),
            ),
          )
          as String);

  @override
  String logoutError(String? error) =>
      (super.noSuchMethod(
            Invocation.method(#logoutError, [error]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#logoutError, [error]),
            ),
          )
          as String);

  @override
  String notificationBudgetBody(String? spent, String? limit) =>
      (super.noSuchMethod(
            Invocation.method(#notificationBudgetBody, [spent, limit]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#notificationBudgetBody, [spent, limit]),
            ),
          )
          as String);

  @override
  String editExpenseExchangeRateDate(String? date) =>
      (super.noSuchMethod(
            Invocation.method(#editExpenseExchangeRateDate, [date]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#editExpenseExchangeRateDate, [date]),
            ),
          )
          as String);
}
